src/Entity/Recruteur.php
<?php

namespace App\Entity;
use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
/**
 * @ORM\Entity(repositoryClass="App\Repository\RecruteurRepository")
 */
class Recruteur extends User
{

    /**
     * @ORM\Column(type="string", length=12)
     */
    private $cin_recruteur;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom_recruteur;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom_recruteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email_recruteur;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_societe;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $domaine;

    /**
     * @ORM\Column(type="string", length=2000)
     */
    private $description;
      /**
     * @ORM\Column(type="string", length=1000)
     */
    private $adresse;
       /**
     * @ORM\Column(type="string", length=1000)
     */
    private $lien_site;
       /**
     * @ORM\Column(type="string", length=1000)
     */
    private $lien_facebook;
       /**
     * @ORM\Column(type="string", length=1000)
     */
    private $lien_linkedin;
       /**
     * @ORM\Column(type="string", length=45)
     */
    private $telephone;
     /**
     * @ORM\Column(type="string", length=6000)
     */
    private $logo;


/**
 * @ORM\OneToMany(targetEntity="App\Entity\OffreEmploi", mappedBy="recruteur")
 */
private $mesOffres;

public function __construct()
{
    
    $this->mesOffres = new ArrayCollection();
}
  

    public function getCinRecruteur(): ?string
    {
        return $this->cin_recruteur;
    }

    public function setCinRecruteur(string $cin_recruteur): self
    {
        $this->cin_recruteur = $cin_recruteur;

        return $this;
    }

    public function getNomRecruteur(): ?string
    {
        return $this->nom_recruteur;
    }

    public function setNomRecruteur(string $nom_recruteur): self
    {
        $this->nom_recruteur = $nom_recruteur;

        return $this;
    }

    public function getPrenomRecruteur(): ?string
    {
        return $this->prenom_recruteur;
    }

    public function setPrenomRecruteur(string $prenom_recruteur): self
    {
        $this->prenom_recruteur = $prenom_recruteur;

        return $this;
    }

    public function getEmailRecruteur(): ?string
    {
        return $this->email_recruteur;
    }

    public function setEmailRecruteur(string $email_recruteur): self
    {
        $this->email_recruteur = $email_recruteur;

        return $this;
    }


    public function getNomSociete(): ?string
    {
        return $this->nom_societe;
    }

    public function setNomSociete(string $nom_societe): self
    {
        $this->nom_societe = $nom_societe;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDomaine(): ?string
    {
        return $this->domaine;
    }

    public function setDomaine(string $domaine): self
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getLienSite(): ?string
    {
        return $this->lien_site;
    }

    public function setLienSite(string $lien_site): self
    {
        $this->lien_site = $lien_site;

        return $this;
    }

    public function getLienFacebook(): ?string
    {
        return $this->lien_facebook;
    }

    public function setLienFacebook(string $lien_facebook): self
    {
        $this->lien_facebook = $lien_facebook;

        return $this;
    }

    public function getLienLinkedin(): ?string
    {
        return $this->lien_linkedin;
    }

    public function setLienLinkedin(string $lien_linkedin): self
    {
        $this->lien_linkedin = $lien_linkedin;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }


 


    /**
     * @return Collection|OffreEmploi[]
     */
    public function getMesOffres(): Collection
    {
        return $this->mesOffres;
    }

    public function addMesOffre(OffreEmploi $mesOffre): self
    {
        if (!$this->mesOffres->contains($mesOffre)) {
            $this->mesOffres[] = $mesOffre;
            $mesOffre->setRecruteurId($this);
        }

        return $this;
    }

    public function removeMesOffre(OffreEmploi $mesOffre): self
    {
        if ($this->mesOffres->contains($mesOffre)) {
            $this->mesOffres->removeElement($mesOffre);
            // set the owning side to null (unless already changed)
            if ($mesOffre->getRecruteurId() === $this) {
                $mesOffre->setRecruteurId(null);
            }
        }

        return $this;
    }
}

src/Controller/gerer_recruteurController.php
<?php
namespace App\Controller;
use App\Entity\Recruteur;
use App\Form\RecruteurType;
use App\Repository\RecruteurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Forms;



/**
 * @Route("/recruteur")
 */

class gerer_recruteurController extends AbstractController
{
    /**
     * @Route("/gererrecruteur", name="app_gr")
     */
    public function affiche(RecruteurRepository $RecruteurRepository): Response
    {
        $Recruteur = new Recruteur();
        $form = $this->createForm(RecruteurType::class, $Recruteur);

        return $this->render('gerer_recruteur/liste_recruteur.html.twig', [
            'recruteurs' => $RecruteurRepository->findAll(),
            'form' => $form->createView()
        ]
        );
    }
     /**
     * @Route("/", name="recruteur_new", methods={"GET","POST"})
     */
    public function new(Request $request)
    {
        $Recruteur = new Recruteur();
        $form = $this->createForm(RecruteurType::class, $Recruteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Recruteur);
            $entityManager->flush();

            return $this->redirectToRoute('app_gr'
            );
        }
       
    }
    /**
     * @Route("/edit/{id}", name="recruteur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Recruteur $recruteur)
    {
        $em = $this->getDoctrine()->getManager();

        $employee = $em->getRepository('App:Recruteur')->find($recruteur); 
    
       
        $employee->setCinRecruteur($_POST['cin']); 
        $employee->setNomRecruteur($_POST['nom']); 
        $employee->setPrenomRecruteur($_POST['prenom']); 
        $employee->setEmailRecruteur($_POST['email']); 
        $em->persist($employee);
        $em->flush();
        return $this->redirectToRoute('app_gr');
        
    }
  /**
     * @Route("/delete/{id}", name="recruteur_delete", methods={"GET","POST"})
     */
    
    public function delete(Request $request, Recruteur $recruteur): Response
    {
       
        $em = $this->getDoctrine()->getManager();
$tim = $em->getRepository('App:Recruteur')->find($recruteur); 
$em->remove($tim);

// we still need to flush this change to the database
$em->flush();

        return $this->redirectToRoute('app_gr');
    }
}

templates/gerer_recruteur/liste_recruteur.html.twig
{% extends 'base.html.twig' %}


{% block blog %}

<section>
    
    </section>
   
              <div class="header-inner bg-light text-center">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="text-primary">Recruteur</h2>
        <ol class="breadcrumb mb-0 p-0">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item active"> <i class="fas fa-chevron-right"></i> <span>Recruteur</span></li>
        </ol>
      </div>
    </div>
  </div>
</div>
<section class="space-ptb">
  <div class="container">
   <div class="job-filter mb-4 d-sm-flex align-items-center">
          
        <div class="job-alert-bt"> <a class="btn btn-md btn-dark" href="" data-toggle="modal" data-target="#exampleModal13"><i class="fa fa-plus"></i>Ajouter Recruteur </a> </div>
         <!-- Modal -->
<div class="modal fade" id="exampleModal13" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
       <h5 class="modal-title" id="exampleModalLabel">Ajouter Recruteur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" >
      
  
    {% if form is defined %}
{{ form_start(form, {'action': path('recruteur_new')}) }}

     <div class="row">
              <div class="col-md-6 mb-3">
               <div class="form-group">
                   {{ form_row(form.prenom_recruteur, {'attr': {'class': 'form-control','placeholder':'prenom'}}) }}
                </div>
                </div>
                <div class="col-md-6 mb-3">
                   <div class="form-group">
                  {{ form_row(form.nom_recruteur,{'attr': {'class': 'form-control','placeholder':'nom '}}) }}
                </div>
                </div>
        </div>
            <div class="row">
              <div class="col-md-6 mb-3">
               <div class="form-group">
                   {{ form_row(form.cin_recruteur, {'attr': {'class': 'form-control','placeholder':'cin '}}) }}
                </div>
                </div>
                <div class="col-md-6 mb-3">
                   <div class="form-group">
                  {{ form_row(form.email_recruteur,{'attr': {'class': 'form-control','placeholder':'email '}}) }}
                </div>
                </div>
        </div>
           <div class="row">
              <div class="col-md-6 mb-3">
               <div class="form-group">
                   {{ form_row(form.nom_societe, {'attr': {'class': 'form-control','placeholder':'societe'}}) }}
                </div>
                </div>
                <div class="col-md-6 mb-3">
                   <div class="form-group">
                  {{ form_row(form.date,{'attr': {'class': 'form-control','placeholder':'date '}}) }}
                </div>
                </div>
        </div>
                 <div class="row">
              <div class="col-md-6 mb-3">
               <div class="form-group">
                   {{ form_row(form.domaine, {'attr': {'class': 'form-control','placeholder':'domaine'}}) }}
                </div>
                </div>
                <div class="col-md-6 mb-3">
                   <div class="form-group">
                  {{ form_row(form.description,{'attr': {'class': 'form-control','placeholder':'description '}}) }}
                </div>
                </div>
        </div>
                <div class="row">
              
                <div class="col-md-6 mb-3">
                   <div class="form-group">
                  {{ form_row(form.mdp_recruteur,{'attr': {'class': 'form-control','placeholder':'mdp '}}) }}
                </div>
                </div>
        </div>
            <div class="modal-footer">
             {{ form_row(form.ajouter,{'attr': {'class': 'btn btn-primary'}}) }}

                            <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>

                        </div>
{{ form_end(form) }}
{% endif %}

          </div>
         
                        </div>
                    </div>
                </div>
 <!-- end Modal -->
          <div class="job-shortby ml-sm-auto d-flex align-items-center">
            <form class="form-inline">
              <div class="form-group mb-0">
               <input value="search">
              
              </div>
            </form>
          </div>
        </div>
        <div class="row">


    {% for recruteur in recruteurs %}
          <div class="col-12">
            <div class="candidate-list">
              <div class="candidate-list-image">
                <img class="img-fluid" src="/images/avatar/04.jpg" alt="" >
              </div>
              <div class="candidate-list-details">
                <div class="candidate-list-info">
                  <div class="candidate-list-title">
                    <h5 class="mb-0"><a href="#">{{ recruteur.prenomRecruteur }} {{ recruteur.nomRecruteur }}</a></h5>
                  </div>
                  <div class="candidate-list-option">
                    <ul class="list-unstyled">
                      <li><i class="fas fa-envelope pr-1"></i>{{recruteur.emailRecruteur}}  </li>
                      <li><i class="fas fa-file pr-1"></i>{{recruteur.nomSociete}}</li>
                       <li><i class="fas fa-book pr-1"></i>{{recruteur.domaine}}</li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="candidate-list-favourite-time">
                <ul class="list-unstyled mb-0 d-flex">
                      <li><a   href="" data-toggle="modal" data-target="#exampleModal{{recruteur.id}}" title="view" style="margin-right:10px;"><i class="far fa-eye"></i></a></li>
                      <li><a href="" data-toggle="modal" data-target="#exampleModallllll{{recruteur.id}}" class="text-info" data-toggle="tooltip" title="Edit" style="margin-right:10px;"><i class="fas fa-pencil-alt"></i></a></li>
                      <li><a  href="" data-toggle="modal" data-target="#exampleModall1{{recruteur.id}}" class="text-danger" data-toggle="tooltip" title="Delete" style="margin-right:10px;"><i class="far fa-trash-alt"></i></a></li>
                    </ul>
              </div>
            </div>
          </div>
        

          <!-- Modal edit-->
<div class="modal fade" id="exampleModallllll{{recruteur.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
 
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modifier Recruteur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class=" candidate-grid">
         <form method="POST" action="{{ path('recruteur_edit', {'id': recruteur.id}) }}">
              <div class="candidate-list-image">
                <img class="img-fluid" src="/images/avatar/01.jpg" alt="" >
              </div>
              <div class="row">
              <div class="col-md-6 mb-3">
               <div class="form-group">
                  <label>Prenom</label>
                  <input type="text" class="form-control"  name="prenom" id="prenom" value="{{recruteur.prenomRecruteur}}">
                </div>
                   <div class="form-group">
                  <label>Nom</label>
                  <input type="text" class="form-control"  name="nom" id="nom" value="{{recruteur.nomRecruteur}}">
                </div>
                </div>
                
           <div class="col-md-6 mb-3">
               <div class="form-group">
                  <label>Email</label>
                  <input type="text" class="form-control"  name="email" id="email" value="{{recruteur.emailRecruteur}}">
                </div>
                   <div class="form-group">
                  <label>CIN</label>
                  <input type="text"   name="cin" id="cin"  value="{{recruteur.cinRecruteur }}">
                </div>
                </div>
           
              </div>
              </div>
      </div>
    <div class="modal-footer">
    <button type="submit" class="btn btn-xs btn-success">Modifier</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>

                        </div>
               

    </div>
  </div>
   </form>
</div>
 <!-- end Modal -->
 <!-- Modal view -->
<div class="modal fade" id="exampleModal{{recruteur.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Recruteur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class=" candidate-grid">
        
              <div class="candidate-list-image">
                <img class="img-fluid" src="/images/avatar/01.jpg" alt="" >
              </div>
              <div class="row">
              <div class="col-md-6 mb-3">
               <div class="form-group">
                  <label>Prenom</label>
                  <input type="text" class="form-control"  disabled value="{{recruteur.prenomRecruteur}}">
                </div>
                   <div class="form-group">
                  <label>Nom</label>
                  <input type="text" class="form-control"  disabled value="{{recruteur.nomRecruteur}}">
                </div>
                </div>
                
           <div class="col-md-6 mb-3">
               <div class="form-group">
                  <label>Email</label>
                  <input type="text" class="form-control"  disabled value="{{recruteur.emailRecruteur}}">
                </div>
                   <div class="form-group">
                  <label>Societe</label>
                  <input type="text" class="form-control"  disabled value="{{recruteur.nomSociete }}">
                </div>
                </div>
           
              </div>
              </div>
      </div>
    <div class="modal-footer">
  
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>

                        </div>
               

    </div>
  </div>
   
</div>
 <!-- end Modal -->
  <!-- Modal -->
<div class="modal fade" id="exampleModall1{{recruteur.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Supprimer recruteur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" >
         <p><span>Voulez-vous vraiment supprimer <a href="#"></a>  {{ recruteur.nomRecruteur }}? </span></p>

          </div>
          <div class="modal-footer">
          <a  href="{{ path('recruteur_delete', {'id': recruteur.id}) }}"  class="text-danger"  >Supprimerr</a>
                                <button type="button" class="btn btn-default " data-dismiss="modal">Annuler</button>
                               
                            </div>
                        </div>
                    </div>
                </div>
 <!-- end Modal -->
            
           {% else %}
           <ul class="list-unstyled">
                      <li><i class="fas fa-filter pr-1"></i>no records found</li>
            </ul>
 {% endfor %}

 

  <ul class="pagination justify-content-center" style="margin-top:10px; margin-left:900px;">
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">1</a>
             <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul> 

    </div>
    </div>
    </section>
    <br> <br>
{% endblock %}