src/Entity/Candidat.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;
use App\Entity\ExperienceProfissionnelle;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CandidatRepository")
 */
class Candidat extends User
{

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom_candidat;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel_candidat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre_candidat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $domaine_candidat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo_candidat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $linkedin;

    
/**
 * @ORM\OneToMany(targetEntity="App\Entity\ExperienceProfissionnelle", mappedBy="candidat")
 */
private $experiences;

/**
 * @ORM\OneToMany(targetEntity="App\Entity\ReponseCandidat", mappedBy="id_candidat")
 */
private $reponseCandidats;
    



    public function getPrenomCandidat(): ?string
    {
        return $this->prenom_candidat;
    }

    public function setPrenomCandidat(string $prenom_candidat): self
    {
        $this->prenom_candidat = $prenom_candidat;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getTelCandidat(): ?string
    {
        return $this->tel_candidat;
    }

    public function setTelCandidat(string $tel_candidat): self
    {
        $this->tel_candidat = $tel_candidat;

        return $this;
    }

    public function getGenreCandidat(): ?string
    {
        return $this->genre_candidat;
    }

    public function setGenreCandidat(string $genre_candidat): self
    {
        $this->genre_candidat = $genre_candidat;

        return $this;
    }

    public function getDomaineCandidat(): ?string
    {
        return $this->domaine_candidat;
    }

    public function setDomaineCandidat(string $domaine_candidat): self
    {
        $this->domaine_candidat = $domaine_candidat;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPhotoCandidat()
    {
        return $this->photo_candidat;
    }

    public function setPhotoCandidat($photo_candidat)
    {
        $this->photo_candidat = $photo_candidat;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }



    public function __construct()
    {
        $this->experiences = [];
        $this->reponseCandidats = new ArrayCollection();
    }



/** 
 * @return Collection|ExperienceProfissionnelle[]
*/
 public function getExperiences(): Collection
                {
                return $this->experiences;
                }


 public function addExperience(ExperienceProfissionnelle $experience): self
                {
                if (!$this->experiences->contains($experience)) {
                $this->experiences[] = $experience;
                $experience->setCandidat($this);
                }
                return $this;
                }


 public function removeExperience(ExperienceProfissionnelle $experience): self
                {
                if ($this->experiences->contains($experience)) {
                $this->experiences->removeElement($experience);
                // set the owning side to null (unless already changed)
                if ($experience->getCandidat() === $this) {
                $experience->setCandidat(null);
                }
                }
                return $this;
                }



 /**
     * Generates the magic method
     * 
*/
    public function __toString(){
        return  (string)$this->id;
    }

    /**
     * @return Collection|ReponseCandidat[]
     */
    public function getReponseCandidats(): Collection
    {
        return $this->reponseCandidats;
    }

    public function addReponseCandidat(ReponseCandidat $reponseCandidat): self
    {
        if (!$this->reponseCandidats->contains($reponseCandidat)) {
            $this->reponseCandidats[] = $reponseCandidat;
            $reponseCandidat->setIdCandidat($this);
        }

        return $this;
    }

    public function removeReponseCandidat(ReponseCandidat $reponseCandidat): self
    {
        if ($this->reponseCandidats->contains($reponseCandidat)) {
            $this->reponseCandidats->removeElement($reponseCandidat);
            // set the owning side to null (unless already changed)
            if ($reponseCandidat->getIdCandidat() === $this) {
                $reponseCandidat->setIdCandidat(null);
            }
        }

        return $this;
    }


   
}

src/Entity/ExperienceProfissionnelle.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExperienceProfissionnelleRepository")
 */
class ExperienceProfissionnelle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $nom_exp;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

   
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;


/** @ORM\ManyToOne(targetEntity="App\Entity\Candidat", inversedBy="experiences")
 * @ORM\JoinColumn(nullable=false)
 */
 private $candidat;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomExp(): ?string
    {
        return $this->nom_exp;
    }

    public function setNomExp(string $nom_exp): self
    {
        $this->nom_exp = $nom_exp;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }


    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getCandidat(): ?Candidat
        {
           return $this->candidat;
        }
    public function setCandidat(?Candidat $candidat): self
        {
           $this->candidat = $candidat;
           return $this;
        }

}

src/Form/CandidatType.php
<?php

namespace App\Form;

use App\Entity\Candidat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class CandidatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('email',EmailType::class)
            ->add('password',PasswordType::class)
            ->add('confirm_password',PasswordType::class)
            ->add('prenom_candidat')
            ->add('date_naissance')
            ->add('tel_candidat')
            ->add('genre_candidat',ChoiceType::class, [
                'choices' => [
                    'Femme' => 'Femme',
                    'Homme' => 'Homme',
                ]])
            ->add('domaine_candidat',ChoiceType::class, [
                'choices' => [
                    'Energie' => 'Energie',
                    'Ressources Humaines' => 'RH',
                    'IT & Technology' => 'IT',
                    'Gestion ' => 'Gestion',
                    'Informatique ' => 'Informatique',


                ]])
            ->add('adresse')
            ->add('photo_candidat')
            ->add('linkedin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Candidat::class,
        ]);
    }
}

src/Controller/CandidatController.php
<?php

namespace App\Controller;
use App\Entity\Candidat;
use App\Entity\User;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use App\Repository\ExperienceProfissionnelleRepository;
use App\Form\Candidat1;


/**
 * @Route("/candidat")
 */
class CandidatController extends AbstractController
{
/* cette Methode permet de faire la redirection vers  la page qui permet de modifier les données 
du candidat connecté */

     /**
     * @Route("/edit/{id}", name="candidat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request,Candidat $candidat,$id,UserPasswordEncoderInterface $encoder): Response
    {
        //on recupere les donnes de candidat connecte qu'on'a passer son id dans l'url 
        $candidat = $this->getDoctrine()
        ->getRepository(Candidat::class)
        ->find($id);
//on prepare la form a envoyer qui correspond a l'entité candidat 
        $form = $this->createForm(Candidat1::class, $candidat);
        $form->handleRequest($request);
       
        /*Si le user clic sur la boutton sauvegarder de type submit 
        ses donnés seront sauvegardés dand la BD */

        if ($form->isSubmitted() && $form->isValid()) {
           
            $hash = $encoder->encodePassword($candidat,$candidat->getPassword());
            $candidat->setPassword($hash);
           
            $this->getDoctrine()->getManager()->flush();
            $form = $this->createForm(CandidatType::class, $candidat);
            $form->handleRequest($request);
          
/*Aprés la sauvegarde on le redirige vers la méme page de modification avec 
ses donnés mis a jour*/

            return $this->render('candidat/edit.html.twig', [
                'candidat' => $candidat,
                'form1' => $form->createView(),
                'id'=>$id
                ]);        
            }

        
        return $this->render('candidat/edit.html.twig',[
            'candidat' => $candidat,
            'form1' => $form->createView(),
            'id'=>$id
        ]);
    }




    
/* cette Methode permet de faire la redirection vers  la page qui affiche la liste
des candidats */    

    /**
     * @Route("/", name="candidat_index", methods={"GET"})
     */
    public function index(CandidatRepository $candidatRepository): Response
    {
        return $this->render('candidat/index.html.twig', [
            'candidats' => $candidatRepository->findAll(),
        ]);
    }



   

     

    /**
     * @Route("/entretien", name="candidat_entretien", methods={"GET"})
     */
    public function indexEntretien()
    {
        $user = $this->getUser();
        $id=$user->getId(); 
      

        $rawSql4 = "SELECT * FROM `entretien_candidat` as ec,
        `entretien` as e ,`recruteur` as r,
        `offre_emploi` as om WHERE 
         ec.entretien_id_id=e.id and 
         r.id=om.id_recruteur and 
         e.id=om.id_entretien_id and e.id=om.id_entretien_id and ec.candidat_id_id =$id;";

        $can4 = $this->getDoctrine()->getManager();
        $s4 = $can4->getConnection()->prepare($rawSql4);
        $s4->execute([]);
        $result4=$s4->fetchAll();
         
        $date=new \DateTime('now');

        return $this->render('candidat/entretiens.html.twig', ['id' =>$id,
        'entret'=>$result4,
        'date'=>$date,
      
     ]);
    }



    /* cette Methode permet de générer le cv du candidat en extrairant les donnes du 
    condidat conncté  */


     /**
     * @Route("/cv/{id}", name="cv_index", methods={"GET","POST"})
     */
    public function indexcv(Request $request,Candidat $candidat,ExperienceProfissionnelleRepository $experienceProfissionnelleRepository,$id): Response
    {

                //on recupere les donnes de candidat connecte qu'on'a passer son id dans l'url par find(id)


        $candidat = $this->getDoctrine()
        ->getRepository(Candidat::class)
        ->find($id);


        return $this->render('candidat/moncv.html.twig', [
            'experience_profissionnelles' => $experienceProfissionnelleRepository->findAllByCandidat($id),
            'id'=>$id,
            'candidat' => $candidat,

        ]);  }

 
   

}

templates/candidat/edit.html.twig
{# template père base.html.twig  #}
{% extends 'base.html.twig' %}

{% block header %}
{% include "BarCandidat/header.html.twig"  with {'id': id }%}
{% endblock %}
{# le block title est remplacé par l'enfant "experience" #}
{% block title %}Edit Candidat{% endblock %}

{% block body %}

<div class="header-inner bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="candidates-user-info">
          <div class="jobber-user-info">
            <div class="profile-avatar">
 <img class="img-fluid" src="/images/avatar/05.jpg" alt="avatar">
              <i class="fas fa-pencil-alt"></i>
            </div>
            <div class="profile-avatar-info ml-4">
            {# on affiche le prenom de candidat connecté #}
              <h3>{{ candidat.username }}  {{ candidat.prenomCandidat }}</h3>
            </div>
          </div>
        </div>
      </div>
     
    </div>
  </div>
</div>
{% block blog  %}
<!--========================Menu de profil candidat  =========================-->

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="sticky-top secondary-menu-sticky-top">
              <div class="secondary-menu">
                <ul class="list-unstyled mb-0">
                {# on a utulisés la fonction path()  pour créer un lien vers les pages qui peut le recruteur les consultées
               et passez le nom de la route comme premier argument et les paramètres de la route comme deuxième argument  #} 
                  <li><a href= {{ path('candidat_edit', {id:id}) }}>Info Génerale </a></li>
                 
                  <li><a href= {{ path('experience_profissionnelle_index',{id:id}) }}>Info profisionnelle </a></li>


                 <li><a href= {{ path('cv_index',{id:id}) }}>Mon CV</a></li>

                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
   <!--========================Fin Menu de profil candidat  =========================-->
    {% endblock %}


<!--=================================  Les informations de candidat connecté =======================-->
{# Rend la balise de début d'un formulaire. Cet assistant prend en charge l'impression
     de la méthode configurée et l'action cible du formulaire.#}
{{ form_start(form1) }}
    

     <section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="user-dashboard-info-box">
          <div class="section-title-02 mb-2">
            <h4>Information Génerale </h4>
          </div>
          


            <div class="form-row">
              <div class="form-group col-md-3">

        {{ form_row(form1.username, { 'attr': {'class': 'form-control'} }) }}
              </div>
              <div class="form-group col-md-3">
        {{ form_row(form1.prenom_candidat, { 'attr': {'class': 'form-control'} }) }}

              </div>
              <div class="form-group col-md-6">
               

            {{ form_row(form1.email, { 'attr': {'class': 'form-control'} }) }}

              </div>

              <div class="form-group col-md-3">
                <div class="input-group date" id="datetimepicker-01" data-target-input="nearest">
            {{ form_row(form1.date_naissance ,{ 'attr': {'class': 'form-control datetimepicker-input'} }) }}

                  
                </div>
              </div>

              <div class="form-group col-md-3">
            {{ form_row(form1.tel_candidat ,{ 'attr': {'class': 'form-control'} }) }}

              </div>
             



             <div class="form-group col-md-6">

               <div class="form-group col-md-6 select-border">

                    {{ form_row(form1.genre_candidat ,{ 'attr': {'class': 'form-control basic-select'} }) }}

                  </div>
              </div>
             
              <div class="form-group col-md-6 select-border">
               <div class="form-group col-md-6 select-border">

                    {{ form_row(form1.domaine_candidat ,{ 'attr': {'class': 'form-control basic-select'} }) }}

                  </div>
              </div>

              
              
            </div>

        </div>
        <div class="user-dashboard-info-box">
          <div class="section-title-02 mb-3">
            <h4>Vos Liens Socials</h4>
          </div>
            <div class="form-row">
              
              <div class="form-group mb-0 col-md-12">
            {{ form_row(form1.linkedin ,{ 'attr': {'class': 'form-control'} }) }}

              </div>
            </div>
        </div>
         <div class="user-dashboard-info-box">
          <div class="form-group mb-0">
            <h4 class="mb-3">Adresse</h4>
            <div class="form-group">


            {{ form_row(form1.adresse ,{ 'attr': {'class': 'form-control'} }) }}

            </div>
            <div class="company-address-map">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3151.835434509374!2d144.95373531590414!3d-37.817323442021134!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad65d4c2b349649%3A0xb6899234e561db11!2sEnvato!5e0!3m2!1sen!2sin!4v1559039794237!5m2!1sen!2sin"  height="400" allowfullscreen></iframe>
            </div>
          </div>
        </div>

              
        


    <button class="btn btn-md btn-primary">{{ button_label|default('Sauvegarder') }}</button>

{# form_end : Rend la balise de fin d'un formulaire.#}
{{ form_end(form1) }}


{% endblock %}

templates/candidat/entretienpasser.html.twig
{% extends 'base.html.twig' %}


{% block header %}
{% include "BarCandidat/header.html.twig"  with {'id': id }%}
{% endblock %}


{% block body %}
<!--=================================
coming-soon -->
<section class="space-ptb bg-holder coming-soon h-100vh" style="background-image: url(/images/bg/coming-soon.jpg);">
  <div class="container h-100">
    <div class="row h-100">
      <div class="col-lg-7 col-md-9 align-self-center">
        <h1>Vos réponses sont enregistrés.Votre resultat sera servi trés bientot </h1>
        
        
        
        
      </div>
    </div>
  </div>
</section>
<!--=================================
coming-soon -->
{% endblock %}

templates/candidat/entretiens.html.twig
{% include "BarCandidat/header.html.twig" with {id:id}%}


{% block body %}

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="user-dashboard-info-box table-responsive pb-4 mb-0">
          <table class="table manage-candidates-top mb-0">
              
            <thead>
              <tr>
                <th>Entretien</th>
                <th>Société </th>
                 <th>Poste </th>
                <th>Date entretien</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
             {% for en in entret %}
              <tr class="candidates-list">
                <td class="title">
                  {{en.nom_entretien}}
                </td>
                <td class="candidate-list-favourite-time">
                 {{en.nom_societe}}
                </td>
                
                <td class="candidate-list-favourite-time">
                {{en.nom_poste}}
                </td>

                <td class="candidate-list-favourite-time">
             {{en.date_entretien}} 
                            </td>



                <td class="candidate-list-favourite-time">
                    <a href="{{ path('interview', {'ide': en.id}) }}" 
                    class="btn btn-success" > Passer</a>
                </td>



       
              </tr>
            
   
                   {% endfor %}

           
            </tbody>
          </table>
        <div class="row">
          <div class="col-12 text-center mt-3 mb-4 mt-sm-3">
            <ul class="pagination justify-content-center mb-0">
              <li class="page-item disabled"> <span class="page-link b-radius-none">Prev</span> </li>
              <li class="page-item active" aria-current="page"><span class="page-link">1 </span> <span class="sr-only">(current)</span></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">...</a></li>
              <li class="page-item"><a class="page-link" href="#">25</a></li>
              <li class="page-item"> <a class="page-link" href="#">Next</a> </li>
            </ul>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/candidat/interview.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{%set y =0%}
{%set z =0%}
<section class="space-ptb bg-light">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="section-title text-center">
        <h2 class="text-primary">Passer Entretien</h2>
       </div>
      </div>
    
    </div>
  </div>
</section>

     <style>
     .clear {
    clear: both;
}
     </style>     

<section class="space-ptb bg-light">
  <div class="container">
    <div class="row justify-content-center">


          <form class="form-row" method="POST" action="{{ path('reponseCandidat', {'idee': id}) }}">
<div class="clear">
               {% for q in questions %} 
               
               
               <br/> 
               <h2> Question {{z+1}}:</h2> <br/> 
            <h3> {{q.contenu}} </h3> <br/>
            
           {%set i =0%}
            {%for p in propos %}
    {%if q.id == p.id_question_id %}
    
         <div class="custom-control custom-checkbox">
          {%set y =y+1 %}
                <input type="checkbox" class="custom-control-input" id="__name{{y}}__"" name="check{{i}}[]" >
               
            <label class="custom-control-label" for="__name{{y}}__"">{{p.nom_prop}} check{{i}}{{y}} </label> <br/>
             {%set i =i+1%}
          </div>  
          {% endif %}
        
 {% endfor %}
          {% set z=z+1 %}
          
           
           
           {% endfor %}
</div>
<div class="clear">
                  {% for qau in autrequestion %}  
            <h2> Question {{z+1}}:</h2> <br/> 
            <h3 > {{qau.contenu}}</h3>
             <textarea class="form-control" name="reponse[]" rows="4"></textarea> 
            
           {% set z=z+1 %}
           {% endfor %}
           <br/>
<button type="submit" href="/entretienpasser" class="btn btn-lg btn-primary">Enregistrer</button>
</div>
</form> 
</div>
</div>
</section>
{% endblock %}

templates/candidat/moncv.html.twig
      <script src="{{asset ('js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{asset ('js/popper/popper.min.js') }}"></script>
    <script src="{{asset ('js/bootstrap/bootstrap.min.js') }}"></script>

    <!-- Page JS Implementing Plugins (Remove the plugin script here if site does not use that feature)-->
    <script src="{{asset ('js/jquery.appear.js') }}"></script>
    <script src="{{asset ('js/counter/jquery.countTo.js') }}"></script>
    <script src="{{asset ('js/owl-carousel/owl-carousel.min.js') }}"></script>
    <script src="{{asset ('js/magnific-popup/jquery.magnific-popup.min.js') }}"></script>

    <!-- Template Scripts (Do not remove)-->
    <script src="{{asset ('js/custom.js') }}"></script>
          

           <link href="/images/favicon.ico" rel="shortcut icon" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">
   <!-- CSS Global Compulsory (Do not remove)-->
    <link rel="stylesheet" href="{{asset ('css/font-awesome/all.min.css') }}" />
    <link rel="stylesheet" href="{{asset ('css/flaticon/flaticon.css') }}" />
    <link rel="stylesheet" href="{{asset ('css/bootstrap/bootstrap.min.css') }}" />

    <!-- Page CSS Implementing Plugins (Remove the plugin CSS here if site does not use that feature)-->
    <link rel="stylesheet" href=" {{asset ('css/owl-carousel/owl.carousel.min.css') }} " />
    <link rel="stylesheet" href="{{asset ('css/magnific-popup/magnific-popup.css') }}" />

    <!-- Template Style -->
    <link rel="stylesheet" href="{{asset ('css/style.css') }}" />




          
           <!--=================================
    My Resume -->
<section class="space-ptb">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-9">
        <div class="row">
          <div class="col-lg-5">
            <div class="resume-base bg-light user-dashboard-info-box">
              <div class="profile">
                <div class="jobber-user-info">
                  <div class="profile-avatar">
 <img class="img-fluid" src="/images/avatar/05.jpg" alt="avatar">

                  </div>
                  <div class="profile-avatar-info mt-3">
                    <h5>{{ candidat.username }}  {{ candidat.prenomCandidat }}</h5>
                  </div>
                </div>
              </div>
              <div class="about-candidate border-top">
                <div class="candidate-info">
                  <h6>Nom et prenom:</h6>
                  <p>{{ candidat.username }}  {{ candidat.prenomCandidat }}</p>
                </div>
                <div class="candidate-info">
                  <h6>Email:</h6>
                  <p>{{ candidat.email }}</p>
                </div>
                <div class="candidate-info">
                  <h6>Telephone:</h6>
                  <p>{{ candidat.telCandidat }}</p>
                </div>
                <div class="candidate-info">
                  <h6>Date de naissance:</h6>
                  <p>{{ candidat.dateNaissance ? candidat.dateNaissance|date('Y-m-d') : '' }}</p>
                </div>
                <div class="candidate-info">
                  <h6>Adresse:</h6>
                  <p>{{ candidat.adresse }}</p>
                </div>
                <div class="candidate-info">
                  <h6>Genre:</h6>
                  <p>{{ candidat.genreCandidat }}</p>
                </div>
                <p>The old expression is absolutely true – whether you think you can or you can’t, you’re right!   One of the main areas that I work on with my clients is shedding these non-supportive beliefs and replacing them with beliefs that will help them to accomplish their desires.</p>
              </div>
            </div>
          </div>
         
              <div class="timeline-box mt-4">
                <h5 class="resume-experience-title"> Experience:</h5>



                 {% for experience_profissionnelle in experience_profissionnelles %}

          <div class="collapse show" id="dateposted">
            
          </div>
          <div class="jobber-candidate-timeline mt-4">
            <div class="jobber-timeline-icon">
              <i class="fas fa-graduation-cap"></i>
            </div>
            <div class="jobber-timeline-item">
              <div class="jobber-timeline-cricle">
                <i class="far fa-circle"></i>
              </div>
              <div class="jobber-timeline-info">
                <div class="dashboard-timeline-info">
                 



                  <span class="jobber-timeline-time">{{ experience_profissionnelle.dateDebut ? experience_profissionnelle.dateDebut|date('Y-m-d') : '' }}</span>
                 <span class="jobber-timeline-time">{{ experience_profissionnelle.dateFin ? experience_profissionnelle.dateFin|date('Y-m-d') : '' }}</span>
                  <h6 class="mb-2">{{ experience_profissionnelle.nomExp }}</h6>
                  <span>- {{ experience_profissionnelle.entreprise }}</span>
                  <p class="mt-2">{{ experience_profissionnelle.description }}</p>
                </div>

</div>
            </div>
            </div>
              {% endfor %}


               
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--=================================
My Resume -->

    <!--=================================
    Back To Top-->
    <div id="back-to-top" class="back-to-top">
      <i class="fas fa-angle-up"></i>
    </div>
    <!--=================================
    Back To Top-->

 <div class="col-lg-2 text-lg-right">

        <a class="btn btn-primary btn-md mb-4 mb-lg-0" href={{ path('acceuil') }}>Retour </a>
      </div>